version: '3.8'

services:
  minio_main:
    user: root
    container_name: minio_main
    image: docker.io/bitnami/minio:2024.3.15
    deploy:
      resources:
        reservations:
          cpus: "20.0"
    environment:
      - MINIO_SERVER_URL=http://154.197.14.86
      - MINIO_BROWSER_REDIRECT_URL=http://154.197.14.86/minio-console
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - /opt/minio/data:/bitnami/minio/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://154.197.14.86:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - minio_network
  nginx_minio:
    user: root
    container_name: nginx_minio
    image: docker.io/bitnami/nginx:1.25.2
    deploy:
      resources:
        reservations:
          cpus: "5.0"
    depends_on:
      minio_main:
        condition: service_healthy
    ports:
      - 80:80
    volumes:
      - ./nginx-alpine/conf:/opt/bitnami/nginx/conf/server_blocks
      - ./nginx-alpine/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf:ro
    restart: unless-stopped
    healthcheck:
      test: "if [ -e /opt/bitnami/nginx/tmp/nginx.pid ]; then exit 0; else exit 1; fi"
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - minio_network

networks:
  minio_network:
    driver: bridge
