version: '3.8'

services:
  minio_main:
    user: root
    container_name: minio_main
    image: docker.io/bitnami/minio:2024.3.15
    deploy:
      resources:
        reservations:
          cpus: "20.0"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_SERVER_URL=http://206.119.83.31
      - MINIO_BROWSER_REDIRECT_URL=http://206.119.83.31/minio-console
    volumes:
      - /opt/minio/data:/bitnami/minio/data
    restart: unless-stopped
    healthcheck:
      test: "curl -s -o /dev/null -w '%{http_code}' 127.0.0.1:9000/minio/health/live | grep 200 || exit 1"
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - minio_network
  nginx_minio:
    user: root
    container_name: nginx_minio
    image: docker.io/bitnami/nginx:1.25.2
    deploy:
      resources:
        reservations:
          cpus: "5.0"
    depends_on:
      minio_main:
        condition: service_healthy
    ports:
      - 80:80
    volumes:
      - ./nginx-alpine/conf:/opt/bitnami/nginx/conf/server_blocks
      - ./nginx-alpine/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf:ro
    restart: unless-stopped
    healthcheck:
      test: "if [ -e /opt/bitnami/nginx/tmp/nginx.pid ]; then exit 0; else exit 1; fi"
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - minio_network

networks:
  minio_network:
    driver: bridge
