version: '1.0'

services:
  minio_main:
    user: root
    container_name: minio_main
    image: docker.io/bitnami/minio:2023.10.7
    environment:
      - MINIO_SERVER_URL=http://154.197.14.86
      - MINIO_BROWSER_REDIRECT_URL=http://154.197.14.86/minio-console
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - /opt/minio/data:/bitnami/minio/data
    networks:
      - minio_network
  nginx_minio:
    user: root
    container_name: nginx_minio
    image: docker.io/bitnami/nginx:1.25.2
    depends_on:
      minio_main:
        condition: service_started
    ports:
      - 80:80
    volumes:
      - ./nginx-alpine/conf:/opt/bitnami/nginx/conf/server_blocks
      - ./nginx-alpine/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf:ro
    networks:
      - minio_network

networks:
  minio_network:
    driver: bridge
